  
apiVersion: v1
kind: Service
metadata:
  name: relay-service
spec:
  type: NodePort
  selector:
    app: relay-depl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30900
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-depl
spec:
  selector:
    matchLabels:
      app: relay-depl
  replicas: 1
  template:
    metadata:
      labels:
        app: relay-depl
    spec:
      containers:
      - name: relay
        image: rupesh40/relay:v1
        ports:
        - containerPort: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: relay-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "127.0.0.1"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: relay-vs
spec:
  hosts:
  - "127.0.0.1"
  gateways:
  - relay-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: relay-service
        port:
          number: 80